# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "deployment"
  deployment:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    environment: production

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      # - name: checkout
      #   uses: actions/checkout@v3 # https://github.com/actions/checkout
      
      - name: deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            # git update to latest codebase on main branch
            cd /www/blh.im && git pull
      # - name: deploy
      #   uses: AEnterprise/rsync-deploy@v1.0 # https://github.com/AEnterprise/rsync-deploy
      #   env:
      #     DEPLOY_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      #     ARGS: -avz --delete # must have this variable
      #     SERVER_PORT: ${{ secrets.SSH_PORT }}
      #     SERVER_IP: ${{ secrets.SSH_HOST }}
      #     USERNAME: ${{ secrets.SSH_USERNAME }}
      #     FOLDER: ./ # folder to push (./ is the root of current repo)
      #     SERVER_DESTINATION: /www/index/ # the directory of the remote server

#       # Runs a single command using the runners shell
#       - name: Run a one-line script
#         run: echo Hello, world!

#       # Runs a set of commands using the runners shell
#       - name: Run a multi-line script
#         run: |
#           echo Add other actions to build,
#           echo test, and deploy your project.
